/**
 * Assemble a clean deploy directory (site/) from the project root.
 *
 * The repository root doubles as the live site during local development
 * (index.html -> css/, dist/, data/). Deploy targets must NOT ship
 * node_modules/, src/, scripts/ or other dev-only files, no matter whether
 * they are ignored by git or not (e.g. GitHub Actions upload-pages-artifact
 * does not read .gitignore).
 *
 * This script copies exactly what a browser needs into site/:
 *   - index.html
 *   - css/        (styles)
 *   - dist/       (TypeScript build output, generated by `npm run build`)
 *   - data/       (GeoJSON fallbacks, demo CSVs and the Excel template)
 * Source maps (*.map) are skipped to keep the published bundle lean.
 *
 * Both deploy pipelines consume this single artifact:
 *   - GitHub Pages: .github/workflows/deploy.yml uploads site/
 *   - EdgeOne Pages: edgeone.json -> buildCommand "npm run build:site",
 *                    outputDirectory "./site"
 *
 * Usage: npm run build:site   (or: node scripts/assemble-site.mjs)
 */
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const SITE = join(ROOT, 'site');

/** Top-level items a browser needs at runtime. */
const ITEMS = ['index.html', 'css', 'dist', 'data'];

/** Recursive size (bytes) of a directory. */
function dirSize(dir) {
  let bytes = 0;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name);
    bytes += entry.isDirectory() ? dirSize(p) : statSync(p).size;
  }
  return bytes;
}

rmSync(SITE, { recursive: true, force: true });
mkdirSync(SITE, { recursive: true });

for (const item of ITEMS) {
  const from = join(ROOT, item);
  if (!existsSync(from)) {
    console.warn(`[assemble] skipped (missing): ${item}`);
    continue;
  }
  // filter callback drops any source whose path ends with .map
  cpSync(from, join(SITE, item), {
    recursive: true,
    filter: (src) => !src.endsWith('.map')
  });
}

console.log('[assemble] site/ assembled from: ' + ITEMS.join(', '));
for (const item of ITEMS) {
  const p = join(SITE, item);
  if (existsSync(p)) {
    const stat = statSync(p);
    const bytes = stat.isDirectory() ? dirSize(p) : stat.size;
    console.log(`  site/${item.padEnd(12)} ${(bytes / 1024).toFixed(1)} KB`);
  }
}
const totalKb = (dirSize(SITE) / 1024).toFixed(1);
console.log(`[assemble] total site size: ${totalKb} KB -> ready to deploy`);
