/**
 * Type definitions for the China Heatmap application.
 * All shared types live here to avoid circular imports.
 */

/**
 * Hierarchical parsed row from the uploaded file.
 *
 * Required structure: 4 columns (省 / 市 / 区县 / 数值).
 *   - province is ALWAYS required
 *   - city is optional (must be filled if district is filled)
 *   - district is optional (must be empty if not applicable)
 *   - value must be a parsable number
 *
 * "Filled district must have city + province" and "filled city must have province"
 * are enforced by the validator. Empty cells in the city/district columns are
 * allowed as long as the hierarchy stays valid.
 */
export interface HierarchicalRegion {
  province: string;
  city: string | null;
  district: string | null;
  value: number | null;
}

/**
 * Flat display row used by table/sidebar/export. Carries the hierarchy so we
 * can still recompute aggregations and reconstruct the path on demand.
 */
export interface RegionData {
  /** Display label, e.g. "广东省/广州市/越秀区". */
  region: string;
  value: number | null;
  province: string;
  city: string | null;
  district: string | null;
}

/** Current map view: level (0=country, 1=province, 2=city, 3=district), adcode, name. */
export interface ViewState {
  level: number;
  adcode: string;
  name: string;
}

/** Navigation stack item (same shape as ViewState). */
export type NavItem = ViewState;

/** Full hierarchy path of the current map view (for value lookup). */
export interface ViewPath {
  province: string | null;
  city: string | null;
  district: string | null;
}

/** GeoJSON feature properties provided by DataV. */
export interface GeoFeatureProperties {
  name: string;
  adcode?: number | string;
  adcode_new?: number | string;
  level?: string;
  childrenNum?: number;
  parent?: { adcode?: number | string };
}

/** A single GeoJSON feature. */
export interface GeoFeature {
  type: string;
  properties: GeoFeatureProperties;
  geometry?: {
    type: string;
    coordinates: unknown;
  } | null;
}

/** GeoJSON FeatureCollection. */
export interface GeoJson {
  type: string;
  features: GeoFeature[];
}

/** Sort state for the data table. */
export interface SortState {
  key: 'region' | 'value' | null;
  dir: 'asc' | 'desc';
}

/**
 * Issues detected during data validation. Any populated field means the file
 * is rejected and the user must re-upload a corrected file.
 */
export interface ParseIssues {
  hasIssues: boolean;
  duplicateHeaders: string[];
  emptyRegionRows: number;
  badValueRows: number;
  totalRows: number;
  /** "Filled city without province" or "filled district without city/province". */
  missingParentRows: { row: number; detail: string }[];
  /** "Filled district only" (no province, no city) — rejected with a hint. */
  districtOnlyRows: { row: number; detail: string }[];
  /** Duplicate (province, city, district) tuples. */
  duplicatePathRows: { path: string; row: number }[];
  /** Row number where the missing required header (省/市/区县/数值) was found. */
  missingHeader?: string;
}

/** A province entry from the offline region index (data/region-index.json). */
export interface ProvinceEntry {
  name: string;
  adcode: number;
  /** City names (empty for direct municipalities / regions without a city level). */
  cities: string[];
}

/** A city -> province mapping entry. */
export interface CityEntry {
  city: string;
  province: string;
}

/**
 * Offline region index generated by scripts/gen-template.mjs.
 * Used at runtime to auto-fill the province when only a city name is given.
 */
export interface RegionIndex {
  provinceIndex: ProvinceEntry[];
  cityIndex: CityEntry[];
}

/** A single row parsed from the uploaded file (raw row). */
export type RawRow = Record<string, unknown>;

/** Map used to look up a region's value by its (normalized) name. */
export type RegionValueMap = Map<string, number | null>;
